CREATE TABLE DEPT (
deptno NUMBER PRIMARY KEY,
dept_name VARCHAR(30) NOT NULL,
Loc VARCHAR(30) NOT NULL
);
CREATE TABLE Emp(
  empno NUMBER PRIMARY KEY,
  emp_name VARCHAR(30) NOT NULL,
  Job VARCHAR(30) NOT NULL,
  Salary NUMBER NOT NULL,
  deptno NUMBER NOT NULL,
  CONSTRAINT fk_Dept FOREIGN KEY (deptno) REFERENCES DEPT(deptno)
);
